--drop table usuario;
Create table usuario(
id serial,
documento bigint  not null,
nombre varchar(20) not null,
apellido varchar(20) not null,
fechanacimiento date not null,
telefono varchar(10) not null,
correo varchar(50) not null,
username varchar(20) not null,
pass     varchar(20) not null,
primary key (ID),
UNIQUE (documento));


--drop table CINE;
CREATE TABLE CINE(
	IDCINE serial,
	NOMBRE VARCHAR(40) NOT NULL,
	DIRECCION VARCHAR(40) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	CONSTRAINT PK_CINE PRIMARY KEY (IDCINE));
	
	
	


--drop table pelicula cascade;
CREATE TABLE PELICULA
(
 IDPELICULA serial,
 TITULO VARCHAR(50) NOT NULL,
 DURACION TIME NOT NULL,
 GENERO VARCHAR(50) NOT NULL,
 PORTADA VARCHAR(100) NULL,
 CONSTRAINT PK_PELICULA PRIMARY KEY (IDPELICULA)
);




--DROP TABLE SALA;

CREATE TABLE SALA 
(
 IDSALA serial,
 IDCINE INT NOT NULL,
 NOMBRE VARCHAR NOT NULL,
 DESCRIPCION VARCHAR(50) NOT NULL,
 ASIENTOS INT NOT NULL,
 CONSTRAINT PK_SALA PRIMARY KEY (IDSALA),
 CONSTRAINT FK_SALA_CINE FOREIGN KEY (IDCINE) REFERENCES CINE(IDCINE)
);




--DROP TABLE FUNCION ;
CREATE TABLE funcion

(
 IDfuncion serial,
 IDPELICULA INT NOT NULL,
 IDSALA INT NOT NULL,
 HORAINICIO TIME NOT NULL,
 FECHA DATE NOT NULL,
 CONSTRAINT PK_CARTELERA PRIMARY KEY (IDFUNCION),
 CONSTRAINT FK_CARTELERA_PELICULA FOREIGN KEY (IDPELICULA) REFERENCES PELICULA(IDPELICULA),
 CONSTRAINT FK_CARTELERA_SALA FOREIGN KEY (IDSALA) REFERENCES SALA(IDSALA)

);

CREATE TABLE ASIENTO
(
 IDASIENTO serial,
 NROASIENTO INT NOT NULL,
 IDSALA INT NOT NULL,
 CONSTRAINT PK_ASIENTO PRIMARY KEY (IDASIENTO),
 CONSTRAINT FK_ASIENTO_SALA FOREIGN KEY (IDSALA) REFERENCES SALA(IDSALA)
);


--drop table reserva;
CREATE TABLE RESERVA
(
IDRESERVA SERIAL,
IDFUNCION INT NOT NULL,
IDCLIENTE INT NOT NULL,
IDASIENTO INT NOT NULL,
 CONSTRAINT PK_RESERVA PRIMARY KEY (IDRESERVA),
 CONSTRAINT FK_RESERVA_FUNCION FOREIGN KEY (IDFUNCION) REFERENCES FUNCION(IDFUNCION),
 CONSTRAINT FK_RESERVA_ASIENTO FOREIGN KEY (IDASIENTO) REFERENCES ASIENTO(IDASIENTO),
 CONSTRAINT FK_RESERVA_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES USUARIO(ID),
 unique (idfuncion,idasiento)

);




